config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: :index
  resources :child_anniversaries do
    resources :child_posts
  end

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  get :about, to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get :favorites, to: 'favorites#index'
  post   "favorites/:child_post_id/create"  => "favorites#create"
  delete "favorites/:child_post_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :edit, :update, :destroy]
  get '/child_post/hashtag/:name' => 'child_posts#hashtag'
  get '/child_post/hashtag' => 'child_posts#hashtag'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :child_post
  validates :user_id, presence: true
  validates :child_post_id, presence: true
  validates :content, presence: true, length: { maximum: 50 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @child_post = ChildPost.find(params[:child_post_id])
    @user = @child_post.user
    @comment = @child_post.comments.build(user_id: current_user.id,
                                          content: params[:comment][:content])
    if !@child_post.nil? && @comment.save
      flash[:success] = "コメントを追加しました！"

      if @user != current_user
        @user.notifications.create(child_post_id: @child_post.id, variety: 2,
                                   from_user_id: current_user.id,
                                   content: @comment.content) # コメントは通知種別2
        @user.update_attribute(:notification, true)
      end
    else
      flash[:danger] = "空のコメントは投稿できません。" + @comment.errors.full_messages.join(", ")
    end
    redirect_to request.referrer
  end

  def edit
    @comment = Comment.find(params[:id])
    @child_post = @comment.child_post
    @child_anniversary = @child_post.child_anniversary
    unless @comment.user_id == current_user.id
      flash[:danger] = "他人のコメントは編集できません"
      redirect_to child_anniversary_child_post_path(@child_post.child_anniversary, @child_post)
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @child_post = @comment.child_post
    @child_anniversary = @child_post.child_anniversary
    if @comment.update(comment_params)
      flash[:success] = "コメントが更新されました"
      redirect_to child_anniversary_child_post_path(@child_post.child_anniversary, @child_post)
    else
      redirect_to child_anniversary_child_posts_path
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @child_post = @comment.child_post
    @child_anniversary = @child_post.child_anniversary

    if current_user.id == @comment.user_id
      @comment.destroy
      flash[:success] = "コメントを削除しました"
    end
    redirect_to child_anniversary_child_post_path(@child_anniversary, @child_post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)  # :content は保存したいコメントの属性です
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% comment_user = User.find(comment.user_id) %>
<li id="comment-<%= comment.id %>">
  <div class="row">
    <div class="col-md-1">
      <span class="user"><%= link_to comment_user.username, comment_user %></span>
    </div>
    <div class="col-md-7">
      <span class="comment"><%= comment.content %></span>
    </div>
    <div class="col-md-2 comment-meta font-alt">
      <%= time_ago_in_words(comment.created_at) %>前</span>
    </div>
    <div class="col-md-2">
      <% if current_user.id == comment.user_id %>
        <%= link_to "編集", edit_comment_path(comment)%>
      <% end %>
      <% if current_user.id == comment.user_id %>
        <%= link_to "削除", comment_path(comment), method: :delete,
                                      data: { confirm: "本当に削除しますか？" } %>
      <% end %>
    </div>
  </div>
</li>

app/views/comments/_comment_count.html.erb
<div class="comment-count">
  <i class="far fa-comments"></i>
  <span><%= child_post.comments.count %></span>
</div>

app/views/comments/_feed_comments.html.erb
<% if @comments.any? %>
  <div class="comment clearfix">
    <%= render @comments %>
  </div>
<% end %>

app/views/comments/_new.html.erb
<div class="comment_form">
  <%= render 'comments/new_form' %>
</div>

app/views/comments/_new_form.html.erb
<%= form_for(@comment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= hidden_field_tag :child_post_id, @child_post.id %>
  <div class="comment-form">
    <h4 class="comment-form-title font-alt">Add your comment</h4>
    <form method="post">
      <div class="form-group">
        <%= f.text_area :content, placeholder: "Comment..." %>
      </div>
      <%= f.submit "Post comment", class: "btn btn-round btn-d" %>
    </form>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="comment_form">
  <%= render 'comments/new_form' %>
</div>