config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: :index
  resources :child_anniversaries do
    resources :child_posts
  end

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  get :about, to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get :favorites, to: 'favorites#index'
  post   "favorites/:child_post_id/create"  => "favorites#create"
  delete "favorites/:child_post_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :edit, :update, :destroy]
  get '/child_post/hashtag/:name' => 'child_posts#hashtag'
  get '/child_post/hashtag' => 'child_posts#hashtag'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      次のエラーが発生しました：
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <section class="module">
    <div class="container">
      <div class="row multi-columns-row">
        <% @feed_items.each do |feed_item| %>
          <div class="col-sm-6 col-md-4 col-lg-4">
            <%= link_to child_anniversary_child_post_path(feed_item.child_anniversary, feed_item) do %>
              <div class="gallery-item">
                <div class="gallery-image">
                  <%= render feed_item ,only_image: true %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </section>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat"><%= @user.following.count %></strong>人をフォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat"><%= @user.followers.count %></strong>人のフォロワー
  </a>
</div>