config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: :index
  resources :child_anniversaries do
    resources :child_posts
  end

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  get :about, to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get :favorites, to: 'favorites#index'
  post   "favorites/:child_post_id/create"  => "favorites#create"
  delete "favorites/:child_post_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :edit, :update, :destroy]
  get '/child_post/hashtag/:name' => 'child_posts#hashtag'
  get '/child_post/hashtag' => 'child_posts#hashtag'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/child_anniversary.rb
class ChildAnniversary < ApplicationRecord
  belongs_to :user
  has_one :child_post, dependent: :destroy
  scope :desc_order, -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 100 }
end

app/controllers/child_anniversaries_controller.rb
class ChildAnniversariesController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
    @child_anniversaries = current_user.child_anniversaries.desc_order.paginate(page: params[:page])
  end

  def show
    @child_anniversary = ChildAnniversary.find(params[:id])
  end

  def new
    @child_anniversary = ChildAnniversary.new
  end

  def edit
    @child_anniversary = ChildAnniversary.find(params[:id])
  end

  def update
    @child_anniversary = ChildAnniversary.find(params[:id])
    if @child_anniversary.update(child_anniversary_params)
      flash[:success] = "記念日情報が更新されました"
      redirect_to child_anniversaries_path
    else
      render 'edit'
    end
  end

  def create
    @child_anniversary = current_user.child_anniversaries.build(child_anniversary_params)
    if @child_anniversary.save
      flash[:success] = "記念日登録"
      redirect_to child_anniversaries_path
    else
      render 'new'
    end
  end

  def destroy
    @child_anniversary = ChildAnniversary.find(params[:id])
    if current_user.admin? || current_user?(@child_anniversary.user)
      @child_anniversary.destroy
      flash[:success] = "記念日を削除しました"
      redirect_to child_anniversaries_path
    else
      flash[:danger] = "他人の記念日は削除できません"
      redirect_to child_anniversaries_path
    end
  end

  private

  def child_anniversary_params
    params.require(:child_anniversary).permit(:name, :date, :description)
  end

  def correct_user
    @child_anniversary = current_user.child_anniversaries.find_by(id: params[:id])
    redirect_to root_url if @child_anniversary.nil?
  end
end

app/helpers/child_anniversaries_helper.rb
module ChildAnniversariesHelper
end

app/views/child_anniversaries/_child_anniversary.html.erb
<div class="card h-100 d-flex flex-column">
  <div class="card-header text-center" style="background-color: transparent; color: #4a4a4a;">
    <h5 class="card-title m-0">
      <%= link_to child_anniversary.name, child_anniversary_path(child_anniversary), class: "text-decoration-none" %>
    </h5>
  </div>
  <% if child_anniversary.child_post && child_anniversary.child_post.image.attached? %>
    <%= image_tag child_anniversary.child_post.image, class: "card-img-top" %>
  <% else %>
    <div class="card-img-top d-flex align-items-center justify-content-center" style="background-color: #f0f0f0; height: 200px;">
      <i class="fas fa-camera fa-3x"></i>
    </div>
  <% end %>
  <div class="card-body flex-grow-1">
    <span class='content'><%= child_anniversary.description %></span></br>
  </div>
  <div class="card-footer text-muted d-flex justify-content-between align-items-center mt-auto">
    <span class='content'><%= child_anniversary.date %></span>
    <% if child_anniversary.child_post.present? %>
      | <%= link_to 'アニバ編集', edit_child_anniversary_child_post_path(child_anniversary, child_anniversary.child_post) %>
    <% else %>
      | <%= link_to 'アニバ新規投稿', new_child_anniversary_child_post_path(child_anniversary) %>
    <% end %>
    <% if current_user.id == child_anniversary.user_id %>
      | <%= link_to '編集', edit_child_anniversary_path(child_anniversary) %>
      | <%= button_to "削除", child_anniversary_path(child_anniversary), 
        method: :delete,
        data: { confirm: "本当に削除しますか?", remote: true },
        class: 'btn btn-danger btn-sm' %>  
    <% end %>
  </div>
</div>

app/views/child_anniversaries/_child_anniversary_form.html.erb
<div class="card pt-5 col-lg-4 mx-auto">
  <%= form_with model: @child_anniversary, local: true do |form| %>
    <% if @child_anniversary.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @child_anniversary.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="form-group row">
      <h2 class= "post-title col-form-label col-lg-12 text-center">記念日登録</h2>
    </div>
    <div class="form-group row">
      <%= form.label :name, "記念日の名前", class: 'col-form-label col-lg-12 text-center' %>
      <div class="col-lg-12">
        <%= form.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <%= form.label :description, "記念日の内容", class: 'col-form-label col-lg-12 text-center' %>
      <div class="col-lg-12">
        <%= form.text_area :description, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <%= form.label :date, "記念日の日付", class: 'col-form-label col-lg-12 text-center' %>
      <div class="col-lg-12">
        <%= form.date_field :date, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-lg-12">
        <%= form.submit "保存", class: 'btn btn-primary d-block mx-auto' %>
      </div>
    </div>
  <% end %>
</div>

app/views/child_anniversaries/create.html.erb
<h1>ChildAnniversaries#create</h1>
<p>Find me in app/views/child_anniversaries/create.html.erb</p>

app/views/child_anniversaries/destroy.html.erb
<h1>ChildAnniversaries#destroy</h1>
<p>Find me in app/views/child_anniversaries/destroy.html.erb</p>

app/views/child_anniversaries/edit.html.erb
<% provide(:title, "記念日を編集") %>
<div class="card  pt-5 col-lg-4 mx-auto">
  <%= form_with model: @child_anniversary, local: true do |form| %>
    <% if @child_anniversary.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @child_anniversary.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= form.label :name, "記念日の名前", class: 'd-block text-center' %>
      <%= form.text_field :name, class: 'form-control mx-auto', style: 'width: 80%;' %>
    </div>
    <div class="form-group">
      <%= form.label :description, "記念日の内容", class: 'd-block text-center' %>
      <%= form.text_area :description, class: 'form-control mx-auto', style: 'width: 80%;' %>
    </div>
    <div class="form-group">
      <%= form.label :date, "記念日の日付", class: 'd-block text-center' %>
      <%= form.date_field :date, class: 'form-control mx-auto', style: 'width: 80%;' %>
    </div>
    <%= form.submit "保存", class: 'btn btn-primary d-block mx-auto' %>
  <% end %>
  <%= link_to "記念日を削除する", child_anniversary_path(@child_anniversary), method: :delete, class: 'd-block mx-auto',
                                                                          data: { confirm: "本当にこの記念日を削除してよろしいでしょうか？"} %>
</div>

app/views/child_anniversaries/index.html.erb
<% provide(:title, '記念日一覧') %>
<div class="container">
  <h2 class="module-title font-alt">記念日一覧</h2>
  <p><%= link_to "記念日作成", new_child_anniversary_path, class: "btn btn-primary btn-lg btn-record" %></p>
  <div class="row">
    <% @child_anniversaries.each do |child_anniversary| %>
      <div class="col-md-4 col-lg-4 mb-4">
        <%= render partial: 'child_anniversary', locals: { child_anniversary: child_anniversary } %>
      </div>
    <% end %>
  </div>
  <%= will_paginate @child_anniversaries %>
</div>

app/views/child_anniversaries/new.html.erb
<% provide(:title, "こども記念日登録") %>
<div class="container">
    <div class="row">
      <div class="col-md-offset-3">
        <%= render 'child_anniversaries/child_anniversary_form' %>
      </div>
  </div>
</div>

app/views/child_anniversaries/show.html.erb
<% provide(:title, "#{@child_anniversary.name}") %>
<div class="container">
  <div class="row">
    <h2 class="child_anniversary-name"><%= @child_anniversary.name %></h2>
    <div class="change-child_anniversary">
      <% if current_user == @child_anniversary.user %>
        <%= link_to "編集", edit_child_anniversary_path(@child_anniversary), class: 'edit-child_anniversary' %>
        <%= link_to "削除", child_anniversary_path(@child_anniversary),method: :delete, class: 'delete-child_anniversary',
                                                                           data: { confirm: "本当に削除しますか?" }%>
      <% end %>
    </div>
    <h4><%= @child_anniversary.description %></h4>
      <h5><%= @child_anniversary.date %></h5>
    <% if @child_anniversary.child_post.present? %>
      <h5><%= @child_anniversary.child_post.content %></h5>
    <% end %>
    
    <% if @child_anniversary.child_post&.image&.attached? %>
      <%= image_tag @child_anniversary.child_post.image, size: "50x1000" %>
    <% end %>
  </div>
</div> 

app/views/child_anniversaries/update.html.erb
<h1>ChildAnniversaries#update</h1>
<p>Find me in app/views/child_anniversaries/update.html.erb</p>