config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: :index
  resources :child_anniversaries do
    resources :child_posts
  end

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  get :about, to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get :favorites, to: 'favorites#index'
  post   "favorites/:child_post_id/create"  => "favorites#create"
  delete "favorites/:child_post_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :edit, :update, :destroy]
  get '/child_post/hashtag/:name' => 'child_posts#hashtag'
  get '/child_post/hashtag' => 'child_posts#hashtag'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row copyright">
      <div class="col-md-12 text-center">
        <p>
          <small class="block">&copy; 2020 Your Name All Rights Reserved.</small>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
 <div class="container">
   <%= link_to(image_tag("header_logo.jpg", :alt => "",class: "w-25"), root_url, id: 'logo') %>
   <nav>
     <ul class="navbar navbar-expand-lg bg-body-tertiary">
       <li><%= link_to 'ユーザー登録(無料)',  new_user_registration_path %></li>
       <li><%= link_to 'サインアウト', destroy_user_session_path, method: :delete %></li>
       <li><%= link_to 'アニバポストとは？', about_path %></li>
       <li><%= link_to '利用規約', use_of_terms_path %></li>
       <li><%= link_to 'お気に入り', favorites_path %></li>
     </ul>
   </nav>
 </div>
</header>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <ul class="nav navbar-nav navbar-right">
    <a href="#" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <% if params[:locale] == 'ja' %>
        <%= current_user.LastName %><%= t('nav_honorific') %>
      <% else %>
        <%= current_user.username %>
      <% end %>
    </a>
    <ul class="dropdown-menu dropdown-menu-end">
      <li>
        <%= link_to user_path(current_user), class: 'dropdown-item' do %>
          <i class="fa-solid fa-tachograph-digital"></i> プロフィール
        <% end %>
      </li>
      <li>
        <%= link_to favorites_path, class: 'dropdown-item' do %>
          <i class="fas fa-star"></i> お気に入り
        <% end %>
      </li>
      <li>
        <%= link_to users_path, class: 'dropdown-item' do %>
          <i class="fas fa-user"></i> ユーザー一覧
        <% end %>
      </li>
      <li>
        <% if current_user.notification %>
          <%= link_to notifications_path, class: 'dropdown-item new_notification' do %>
            <i class="fa-solid fa-envelope"></i> <span>通知</span>
          <% end %>
        <% else %>
          <%= link_to notifications_path, class: 'dropdown-item no_notification' do %>
            <i class="fa-solid fa-envelope"></i> <span>通知</span>
          <% end %>
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: 'dropdown-item' do %>
          <i class="fa-solid fa-right-from-bracket"></i>
          <span id="logout_link"><%= t('devise.shared.links.sign_out') %></span>
        <% end %>
      </li>
    </ul>
  </ul>
<% else %>
  <div class="ms-auto">
    <ul class="nav navbar-nav navbar-right">
      <%= link_to t('devise.registrations.new.sign_up'), new_user_registration_path, class: 'btn btn-outline-primary' %>
      <%= link_to t('devise.shared.links.sign_in') ,new_user_session_path, class: 'btn btn-outline-primary' %>
    </ul>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<body data-spy="scroll" data-target=".onpage-navigation" data-offset="60">
  <main>
    <div class="page-loader">
      <div class="loader">Loading...</div>
    </div>
      <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top"  role="navigation">
        <div class="container-fluid">
          <%= link_to 'Anniversary Post', root_path, class: 'navbar-brand' %>

          <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="Navber">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item dropdown">
                <%= link_to 'intro.', "#", class: "nav-link dropdown-toggle", role: "button", "data-bs-toggle" => "dropdown", "aria-expanded" => "false" %>
                <ul class="dropdown-menu">
                  <li><%= link_to 'how to', about_path %></li>
                  <li><%= link_to '利用規約', use_of_terms_path %></li>
                  <li><%= link_to 'Item', '#' %></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><%= link_to 'Item', '#' %></li>
                </ul>
              </li>
              <li class="nav-item">
                <%= link_to '記念日一覧', child_anniversaries_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Menu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">FAQ</a>
              </li>
            </ul>

            <%= render 'layouts/nav_links_for_auth', class: 'ms-auto'  %>

          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
  </main>    
</body>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<script src="https://kit.fontawesome.com/84eeecacff.js" crossorigin="anonymous"></script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(page_title: yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <div id="wrapper"> <%# --- BEGIN of wrapper --- %>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
  
    <%= yield %>
  
    <%# ------ Toastr ----- %>
    <% if flash.any? %>
      <script type="text/javascript">
          <% flash.each do |key, value| %>
          <% key = "success" if key == "notice" %>
          <% key = "error" if key == "alert" || key == "danger" %>
          <% key = "error" if key == "warn" %>
          toastr['<%= key %>']('<%= value %>');
          <% end %>
      </script>
    <% end %>
    <%# ------ Toastr ----- %>
  
  </div> <%# --- END of wrapper --- %>
  </body>
    <%= render 'layouts/footer' %>
  </body>
</html>